## Q1

In [28]:
import numpy as np
nbr = 10
a = np.arange(1,nbr+1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


## Q2

In [29]:
import numpy as np
sampl = np.random.uniform(low=0, high=1, size=(10,))
print(sampl)

[0.55020518 0.78803736 0.76369819 0.03335933 0.4663852  0.59573573
 0.24950373 0.68852316 0.79340535 0.44298131]


## Q3

In [30]:
import numpy as np
a = np.array([4,7,9])
sum_a = np.sum(a)
print(sum_a)

20


## Q4

In [31]:
import numpy as np
a = np.array([4,7,9])
b = np.array([10,20,30])
prdt_scalaire = np.dot(a,b)
print(prdt_scalaire)

450


## Q5

In [32]:
import numpy as np
a = np.array([4,7,9,9,3,4])
array_unic = np.unique(a)
print(array_unic)

[3 4 7 9]


## Q6

In [33]:
import numpy as np
a = np.array([9,5,2,3,7,1])
array_sorted = np.sort(a)
print(array_sorted)

[1 2 3 5 7 9]


## Q7

In [34]:
import numpy as np
a = np.array([9,5,2,3,7,1])
a_moyenne = np.mean(a)
print('moyenne:' + str(a_moyenne))
a_median = np.median(a)
print('médiane:' + str(a_median))
a_ecarttype = np.std(a)
print('écart-type:' + str(a_ecarttype))

moyenne:4.5
médiane:4.0
écart-type:2.8136571693556887


## Q8

In [35]:
import numpy as np
a = np.array([9,5,2,3,7,1])
b = a >= 5
print(b)
c = b.astype(int) 
print(c)

[ True  True False False  True False]
[1 1 0 0 1 0]


## Q9

In [36]:
import numpy as np
sampl = np.random.rand(3,3)
print(sampl)

[[0.6969335  0.96622425 0.25615524]
 [0.46587908 0.24025155 0.76148357]
 [0.51606966 0.33387715 0.75594849]]
